Not Found: /api/products/1/
"GET /api/products/1/ HTTP/1.1" 404 17521
Bad Request: /api/products/4/
"PUT /api/products/4/ HTTP/1.1" 400 18270
Method Not Allowed: /api/orders/create/
"GET /api/orders/create/ HTTP/1.1" 405 11082
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Method Not Allowed: /api/orders/create/
"GET /api/orders/create/ HTTP/1.1" 405 11082
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Method Not Allowed: /api/orders/create/
"GET /api/orders/create/ HTTP/1.1" 405 11082
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Not Found: /api/cart/add/
"GET /api/cart/add/ HTTP/1.1" 404 12605
Method Not Allowed: /api/orders/create/
"GET /api/orders/create/ HTTP/1.1" 405 11082
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Method Not Allowed: /api/orders/create/
"GET /api/orders/create/ HTTP/1.1" 405 11082
Bad Request: /api/orders/create/
"POST /api/orders/create/ HTTP/1.1" 400 11111
Not Found: /api/cart/add/
"GET /api/cart/add/ HTTP/1.1" 404 12605
Method Not Allowed: /api/cart/add_item/
"GET /api/cart/add_item/ HTTP/1.1" 405 11200
Internal Server Error: /api/cart/add_item/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\cart\views.py", line 54, in post
    if product.is_low_stock():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'is_low_stock'
"POST /api/cart/add_item/ HTTP/1.1" 500 97001
Method Not Allowed: /api/cart/add_item/
"GET /api/cart/add_item/ HTTP/1.1" 405 11200
Bad Request: /api/cart/add_item/
"POST /api/cart/add_item/ HTTP/1.1" 400 11179
Bad Request: /api/cart/add_item/
"POST /api/cart/add_item/ HTTP/1.1" 400 11179
Not Found: /products/product/3/change/
"GET /products/product/3/change/ HTTP/1.1" 404 3155
Not Found: /products/product/3
"GET /products/product/3 HTTP/1.1" 404 3131
Not Found: /api/products/{3}/
"GET /api/products/%7B3%7D/ HTTP/1.1" 404 17548
Not Found: /api/products/{3}/
"PUT /api/products/%7B3%7D/ HTTP/1.1" 404 17548
Method Not Allowed: /api/cart/add_item/
"GET /api/cart/add_item/ HTTP/1.1" 405 11200
Bad Request: /api/cart/add_item/
"POST /api/cart/add_item/ HTTP/1.1" 400 11195
Bad Request: /api/cart/add_item/
"POST /api/cart/add_item/ HTTP/1.1" 400 11222
Bad Request: /api/cart/add_item/
"POST /api/cart/add_item/ HTTP/1.1" 400 11179
Internal Server Error: /api/cart/add_item/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\cart\views.py", line 62, in post
    if product.is_low_stock():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'is_low_stock'
"POST /api/cart/add_item/ HTTP/1.1" 500 96944
Method Not Allowed: /api/cart/add_item/
"GET /api/cart/add_item/ HTTP/1.1" 405 11200
Internal Server Error: /api/cart/add_item/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\cart\views.py", line 62, in post
    if product.is_low_stock():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'is_low_stock'
"POST /api/cart/add_item/ HTTP/1.1" 500 96944
Method Not Allowed: /api/cart/add_item/
"GET /api/cart/add_item/ HTTP/1.1" 405 11200
Bad Request: /api/cart/add_item/
"POST /api/cart/add_item/ HTTP/1.1" 400 11187
Internal Server Error: /api/cart/add_item/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\cart\views.py", line 62, in post
    if product.is_low_stock():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'is_low_stock'
"POST /api/cart/add_item/ HTTP/1.1" 500 96944
Method Not Allowed: /api/cart/add_item/
"GET /api/cart/add_item/ HTTP/1.1" 405 11200
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Bad Request: /api/cart/add_item/
"POST /api/cart/add_item/ HTTP/1.1" 400 11187
Bad Request: /api/products/3/
"PUT /api/products/3/ HTTP/1.1" 400 17852
Not Found: /api/rentals/create/
"GET /api/rentals/create/ HTTP/1.1" 404 17496
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17546
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /api/rentals/create/
"GET /api/rentals/create/ HTTP/1.1" 404 17496
Bad Request: /api/rentals/
"POST /api/rentals/ HTTP/1.1" 400 16169
Not Found: /api/rentals/{1}/
"GET /api/rentals/%7B1%7D/ HTTP/1.1" 404 17498
Not Found: /api/rentals/{1}/
"DELETE /api/rentals/%7B1%7D/ HTTP/1.1" 404 17501
Not Found: /api/rentals/{1}/
"GET /api/rentals/%7B1%7D/ HTTP/1.1" 404 17498
Bad Request: /api/products/3/
"PUT /api/products/3/ HTTP/1.1" 400 17852
Not Found: /api/rentals/3/
"PUT /api/rentals/3/ HTTP/1.1" 404 17470
Not Found: /api/rentals/3/
"PATCH /api/rentals/3/ HTTP/1.1" 404 17472
Not Found: /api/rentals/3/
"PUT /api/rentals/3/ HTTP/1.1" 404 17470
Not Found: /api/rentals/3/
"GET /api/rentals/3/ HTTP/1.1" 404 17470
Not Found: /api/rentals/
"POST /api/rentals/ HTTP/1.1" 404 16146
Not Found: /api/rentals/3/
"GET /api/rentals/3/ HTTP/1.1" 404 17470
Bad Request: /api/products/3/
"PATCH /api/products/3/ HTTP/1.1" 400 17546
Bad Request: /api/rentals/
"POST /api/rentals/ HTTP/1.1" 400 16152
Not Found: /
"GET / HTTP/1.1" 404 3059
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /api/products/1/
"GET /api/products/1/ HTTP/1.1" 404 10094
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /api/products/1/
"GET /api/products/1/ HTTP/1.1" 404 10094
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /
"GET / HTTP/1.1" 404 3059
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /products
"GET /products HTTP/1.1" 404 3101
Not Found: /http://localhost:8000/api/products/
"GET /http://localhost:8000/api/products/ HTTP/1.1" 404 3182
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /
"GET / HTTP/1.1" 404 3059
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 10099
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"PATCH /api/products/create/ HTTP/1.1" 404 17258
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"PUT /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"PATCH /api/products/create/ HTTP/1.1" 404 17258
Not Found: /api/create
"GET /api/create HTTP/1.1" 404 11951
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"PUT /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17256
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17566
Not Found: /api/products/create/
"PUT /api/products/create/ HTTP/1.1" 404 17566
Not Found: /api/products/create/
"PATCH /api/products/create/ HTTP/1.1" 404 17568
Not Found: /api/products/create/
"PUT /api/products/create/ HTTP/1.1" 404 17566
Not Found: /
"GET / HTTP/1.1" 404 3059
Not Found: /products
"GET /products HTTP/1.1" 404 3101
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 10099
Not Found: /api/products/create/
"GET /api/products/create/ HTTP/1.1" 404 17566
Not Found: /api/products/create/
"PUT /api/products/create/ HTTP/1.1" 404 17566
Not Found: /api/products/create/
"PATCH /api/products/create/ HTTP/1.1" 404 17568
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /api/blog/reports/
"GET /api/blog/reports/ HTTP/1.1" 404 15828
Not Found: /admin/reports
"GET /admin/reports HTTP/1.1" 404 6967
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /
"GET / HTTP/1.1" 404 3059
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3110
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Not Found: /
"GET / HTTP/1.1" 404 3078
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 58
Not Found: /
"GET / HTTP/1.1" 404 3078
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Not Found: /api/products/{2}
"GET /api/products/%7B2%7D HTTP/1.1" 404 8468
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Not Found: /api/products/2
"GET /api/products/2 HTTP/1.1" 404 8458
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Not Found: /
"GET / HTTP/1.1" 404 3078
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Not Found: /
"GET / HTTP/1.1" 404 3078
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Forbidden: /api/products/categories/
"GET /api/products/categories/ HTTP/1.1" 403 10515
Forbidden: /api/products/categories/
"GET /api/products/categories/ HTTP/1.1" 403 10515
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Not Found: /api/products/2
"GET /api/products/2 HTTP/1.1" 404 8458
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Unauthorized: /api/products/categories/
"GET /api/products/categories/ HTTP/1.1" 401 10100
Forbidden: /api/products/categories/
"GET /api/products/categories/ HTTP/1.1" 403 10515
Not Found: /api
"GET /api HTTP/1.1" 404 3105
Forbidden: /api/products/categories/
"GET /api/products/categories/ HTTP/1.1" 403 10515
Unauthorized: /api/products/
"GET /api/products/ HTTP/1.1" 401 9892
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Unauthorized: /api/products/rentals/
"GET /api/products/rentals/ HTTP/1.1" 401 10070
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Not Found: /api/products/blogs/blogs
"GET /api/products/blogs/blogs HTTP/1.1" 404 8488
Not Found: /api/products/blogs
"GET /api/products/blogs HTTP/1.1" 404 8470
Not Found: /api/products/blog
"GET /api/products/blog HTTP/1.1" 404 8467
Unauthorized: /api/products/categories/
"GET /api/products/categories/ HTTP/1.1" 401 10100
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Unauthorized: /api/products/rentals/
"GET /api/products/rentals/ HTTP/1.1" 401 10070
Not Found: /auth/login/
"POST /auth/login/ HTTP/1.1" 404 3130
Not Found: /auth/login/
"POST /auth/login/ HTTP/1.1" 404 3130
Not Found: /auth/login/
"POST /auth/login/ HTTP/1.1" 404 3130
Not Found: /auth/login/
"POST /auth/login/ HTTP/1.1" 404 3130
Not Found: /
"GET / HTTP/1.1" 404 3078
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Not Found: /api/categories/
"GET /api/categories/ HTTP/1.1" 404 3141
Not Found: /api/categories
"GET /api/categories HTTP/1.1" 404 3138
Not Found: /api/rentals
"GET /api/rentals HTTP/1.1" 404 3129
Not Found: /api/orders
"GET /api/orders HTTP/1.1" 404 3126
Not Found: /api/orders/
"GET /api/orders/ HTTP/1.1" 404 4711
Not Found: /api/categories/
"GET /api/categories/ HTTP/1.1" 404 3141
Not Found: /api/products/categories/
"GET /api/products/categories/ HTTP/1.1" 404 17591
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Not Found: /auth/login/
"POST /auth/login/ HTTP/1.1" 404 3130
Not Found: /auth/register/
"POST /auth/register/ HTTP/1.1" 404 3139
Not Found: /
"GET / HTTP/1.1" 404 3078
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Not Found: /auth/login/
"GET /auth/login/ HTTP/1.1" 404 3129
Not Found: /auth/login/
"GET /auth/login/ HTTP/1.1" 404 3129
Not Found: /products
"GET /products HTTP/1.1" 404 3120
Not Found: /api/auth/login/
"GET /api/auth/login/ HTTP/1.1" 404 3141
Not Found: /api/auth
"GET /api/auth HTTP/1.1" 404 3120
Not Found: /api/register
"GET /api/register HTTP/1.1" 404 3132
Not Found: /auth/register/
"GET /auth/register/ HTTP/1.1" 404 3138
Method Not Allowed: /auth/register/
"GET /auth/register/ HTTP/1.1" 405 13709
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3124
Method Not Allowed: /auth/register/
"GET /auth/register/ HTTP/1.1" 405 13174
Not Found: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 404 3130
Not Found: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 404 3130
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3124
Not Found: /api/users
"GET /api/users HTTP/1.1" 404 3118
Not Found: /api/users
"GET /api/users HTTP/1.1" 404 3118
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3124
Unauthorized: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 401 10037
Unauthorized: /auth/login/
"POST /auth/login/ HTTP/1.1" 401 63
Unauthorized: /auth/login/
"POST /auth/login/ HTTP/1.1" 401 63
Method Not Allowed: /auth/login/
"GET /auth/login/ HTTP/1.1" 405 12548
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3277
Method Not Allowed: /auth/login/
"GET /auth/login/ HTTP/1.1" 405 12548
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3277
Not Found: /
"GET / HTTP/1.1" 404 3078
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3129
Not Found: /auth/login/
"POST /auth/login/ HTTP/1.1" 404 3130
Not Found: /auth/login/
"POST /auth/login/ HTTP/1.1" 404 3130
Method Not Allowed: /auth/login/
"GET /auth/login/ HTTP/1.1" 405 12450
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Not Found: /auth/register/
"GET /auth/register/ HTTP/1.1" 404 3502
Not Found: /auth/register/
"GET /auth/register/ HTTP/1.1" 404 3502
Not Found: /
"GET / HTTP/1.1" 404 3437
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3488
Not Found: /api/auth
"GET /api/auth HTTP/1.1" 404 3479
Not Found: /api/register
"GET /api/register HTTP/1.1" 404 3491
Not Found: /register
"GET /register HTTP/1.1" 404 3479
Not Found: /api/auth/register
"GET /api/auth/register HTTP/1.1" 404 3506
Not Found: /api/auth/register
"GET /api/auth/register HTTP/1.1" 404 3506
Not Found: /api/auth/register
"GET /api/auth/register HTTP/1.1" 404 3506
Method Not Allowed: /auth/register/
"GET /auth/register/ HTTP/1.1" 405 13174
Method Not Allowed: /auth/login/
"GET /auth/login/ HTTP/1.1" 405 12549
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3488
Not Found: /
"GET / HTTP/1.1" 404 3437
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3488
Not Found: /api/users/me
"GET /api/users/me HTTP/1.1" 404 3491
Not Found: /api/users
"GET /api/users HTTP/1.1" 404 3482
Not Found: /api/auth/users/me
"GET /api/auth/users/me HTTP/1.1" 404 3506
Not Found: /api/auth
"GET /api/auth HTTP/1.1" 404 3479
Not Found: /api/auth/users/me
"GET /api/auth/users/me HTTP/1.1" 404 3511
Unauthorized: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 401 10038
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Not Found: /profile_pics/sekiro_2788033b.jpg
"GET /profile_pics/sekiro_2788033b.jpg HTTP/1.1" 404 3556
Unauthorized: /auth/login/
"POST /auth/login/ HTTP/1.1" 401 63
Unauthorized: /auth/login/
"POST /auth/login/ HTTP/1.1" 401 63
Not Found: /profile_pics/sekiro_2788033b.jpg
"GET /profile_pics/sekiro_2788033b.jpg HTTP/1.1" 404 3556
Unauthorized: /auth/login/
"POST /auth/login/ HTTP/1.1" 401 63
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Not Found: /profile_pics/sekiro_2788033b.jpg
"GET /profile_pics/sekiro_2788033b.jpg HTTP/1.1" 404 3556
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Unauthorized: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 401 10088
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Unauthorized: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 401 10088
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16071
Unauthorized: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 401 10088
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Unauthorized: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 401 10088
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /api/users/dashboard/
"GET /api/users/dashboard/ HTTP/1.1" 404 16070
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Internal Server Error: /api/users/dashboard/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\users\views.py", line 37, in admin_dashboard
    blog_count = BlogPost.objects.count()  # Nombre total d'articles de blog
                 ^^^^^^^^
NameError: name 'BlogPost' is not defined
"GET /api/users/dashboard/ HTTP/1.1" 500 100194
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Internal Server Error: /api/users/dashboard/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\users\views.py", line 37, in admin_dashboard
    blog_count = BlogPost.objects.count()  # Nombre total d'articles de blog
                 ^^^^^^^^
NameError: name 'BlogPost' is not defined
"GET /api/users/dashboard/ HTTP/1.1" 500 100194
Internal Server Error: /api/users/dashboard/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\users\views.py", line 38, in admin_dashboard
    "total_blog_posts": BlogPost.objects.count(),  # Nombre total d'articles de blog
                        ^^^^^^^^
NameError: name 'BlogPost' is not defined
"GET /api/users/dashboard/ HTTP/1.1" 500 99887
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Internal Server Error: /api/users/dashboard/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\users\views.py", line 38, in admin_dashboard
    "total_blog_posts": BlogPost.objects.count(),  # Nombre total d'articles de blog
                        ^^^^^^^^
NameError: name 'BlogPost' is not defined
"GET /api/users/dashboard/ HTTP/1.1" 500 99887
Internal Server Error: /api/users/dashboard/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\users\views.py", line 38, in admin_dashboard
    "total_blog_posts": BlogPost.objects.count(),  # Nombre total d'articles de blog
                        ^^^^^^^^
NameError: name 'BlogPost' is not defined
"GET /api/users/dashboard/ HTTP/1.1" 500 99893
Internal Server Error: /api/users/dashboard/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\users\views.py", line 38, in admin_dashboard
    "total_blog_posts": BlogPost.objects.count(),  # Nombre total d'articles de blog
                        ^^^^^^^^
NameError: name 'BlogPost' is not defined
"GET /api/users/dashboard/ HTTP/1.1" 500 99893
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 183
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 183
Unauthorized: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 401 183
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 183
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 183
Unauthorized: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 401 183
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 183
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 183
Not Found: /api
"GET /api HTTP/1.1" 404 3469
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Not Found: /
"GET / HTTP/1.1" 404 3442
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 9886
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /api/orders/
"GET /api/orders/ HTTP/1.1" 404 5075
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3493
Not Found: /
"GET / HTTP/1.1" 404 3442
Not Found: /api/token
"GET /api/token HTTP/1.1" 404 3487
Unauthorized: /api/users/me/
"GET /api/users/me/ HTTP/1.1" 401 10038
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 58
Not Found: /profile_pics/sekiro_2788033b.jpg
"GET /profile_pics/sekiro_2788033b.jpg HTTP/1.1" 404 3556
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"GET /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unauthorized: /api/users/5/
"DELETE /api/users/5/ HTTP/1.1" 401 58
Unauthorized: /api/users/
"POST /api/users/ HTTP/1.1" 401 58
Unsupported Media Type: /api/users/
"POST /api/users/ HTTP/1.1" 415 68
Unsupported Media Type: /api/users/
"POST /api/users/ HTTP/1.1" 415 68
Unsupported Media Type: /api/users/4/
"PUT /api/users/4/ HTTP/1.1" 415 68
Unsupported Media Type: /api/users/4/
"PUT /api/users/4/ HTTP/1.1" 415 68
Unsupported Media Type: /api/users/4/
"PUT /api/users/4/ HTTP/1.1" 415 68
Unsupported Media Type: /api/users/4/
"PUT /api/users/4/ HTTP/1.1" 415 68
Unsupported Media Type: /api/users/4/
"PUT /api/users/4/ HTTP/1.1" 415 68
Bad Request: /api/users/4/
"PUT /api/users/4/ HTTP/1.1" 400 45
Bad Request: /api/users/4/
"PUT /api/users/4/ HTTP/1.1" 400 45
Not Found: /
"GET / HTTP/1.1" 404 3789
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3840
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/redoc.html
"GET /redoc/ HTTP/1.1" 500 92171
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/redoc.html
"GET /redoc/ HTTP/1.1" 500 92171
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/redoc.html
"GET /redoc/ HTTP/1.1" 500 92171
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3842
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/redoc.html
"GET /redoc/ HTTP/1.1" 500 92171
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94365
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94371
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 94371
Not Found: /
"GET / HTTP/1.1" 404 3941
Not Found: /api/schema/swagger-ui/
"GET /api/schema/swagger-ui/ HTTP/1.1" 404 4025
Not Found: /api/schema/swagger
"GET /api/schema/swagger HTTP/1.1" 404 4013
Not Found: /api/schema/redoc/
"GET /api/schema/redoc/ HTTP/1.1" 404 4010
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /swagger/
"GET /swagger/ HTTP/1.1" 404 3983
Not Found: /
"GET / HTTP/1.1" 404 3941
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/redoc
"GET /api/redoc HTTP/1.1" 404 3986
Not Found: /
"GET / HTTP/1.1" 404 3941
Not Found: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 404 10014
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 404 17571
Not Found: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 404 17571
Not Found: /api/products/wishlist/
"PUT /api/products/wishlist/ HTTP/1.1" 404 17571
Not Found: /api/products/wishlist/
"PATCH /api/products/wishlist/ HTTP/1.1" 404 17573
Not Found: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 404 10014
Not Found: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 404 10014
Not Found: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 404 10014
Not Found: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 404 17571
Internal Server Error: /api/products/wishlist/
Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Product'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1835, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1760, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1699, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <Product: Tracteur puissant>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\Master\PycharmProjects\FarmShop\farmshop\products\views.py", line 84, in perform_create
    serializer.save(user=self.request.user)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\serializers.py", line 1008, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Wishlist.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Wishlist.objects.create()`. You may need to make the field read-only, or override the WishlistSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Product'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1835, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1760, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1699, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Master\PycharmProjects\FarmShop\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <Product: Tracteur puissant>.

"POST /api/products/wishlist/ HTTP/1.1" 500 253006
Not Found: /
"GET / HTTP/1.1" 404 3941
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Unauthorized: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 401 10092
Unauthorized: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 401 10092
Unauthorized: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 401 10092
Unauthorized: /api/products/wishlist/
"GET /api/products/wishlist/ HTTP/1.1" 401 10092
Not Found: /
"GET / HTTP/1.1" 404 3941
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/blog/articles/
"GET /api/blog/articles/ HTTP/1.1" 404 10424
Not Found: /api/comments/
"GET /api/comments/ HTTP/1.1" 404 3998
Unauthorized: /api/blog/reports/
"GET /api/blog/reports/ HTTP/1.1" 401 10041
Not Found: /api/blog/blog/
"GET /api/blog/blog/ HTTP/1.1" 404 9745
Not Found: /api/blog/blog/
"GET /api/blog/blog/ HTTP/1.1" 404 9745
Not Found: /api/blog/blog/
"GET /api/blog/blog/ HTTP/1.1" 404 9745
Not Found: /api/blog/blog/
"GET /api/blog/blog/ HTTP/1.1" 404 9745
Not Found: /api/blog/blog/
"GET /api/blog/blog/ HTTP/1.1" 404 9745
Unauthorized: /auth/login/
"POST /auth/login/ HTTP/1.1" 401 63
Not Found: /api/blog/blog/
"GET /api/blog/blog/ HTTP/1.1" 404 9745
Not Found: /api/blog/blog/1/
"GET /api/blog/blog/1/ HTTP/1.1" 404 9751
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/blog/1
"GET /api/blog/1 HTTP/1.1" 404 9733
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/blog/2/
"GET /api/blog/2/ HTTP/1.1" 404 9736
Not Found: /api/blog/1/
"GET /api/blog/1/ HTTP/1.1" 404 9736
Not Found: /api/blog/2/
"GET /api/blog/2/ HTTP/1.1" 404 9736
Not Found: /api/blog/articles
"GET /api/blog/articles HTTP/1.1" 404 9754
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/blog/article
"GET /api/blog/article HTTP/1.1" 404 9751
Not Found: /api/blog/2
"GET /api/blog/2 HTTP/1.1" 404 9733
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=2 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=1 HTTP/1.1" 404 23
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/blog/comments/
"GET /api/blog/comments/ HTTP/1.1" 404 9986
Not Found: /api/commen ts
"GET /api/commen%20ts HTTP/1.1" 404 4000
Not Found: /api/comments
"GET /api/comments HTTP/1.1" 404 3995
Not Found: /api/blog/comments/
"GET /api/blog/comments/ HTTP/1.1" 404 9986
Not Found: /api/comments
"GET /api/comments HTTP/1.1" 404 3995
Not Found: /api/blog/blog/
"GET /api/blog/blog/ HTTP/1.1" 404 9962
Not Found: /api/blog/articles/
"GET /api/blog/articles/ HTTP/1.1" 404 9986
Not Found: /api/blog/report/
"GET /api/blog/report/ HTTP/1.1" 404 9974
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=1 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=2 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=2 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=2 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=1 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=2 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=1 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=1 HTTP/1.1" 404 23
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3992
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=1 HTTP/1.1" 404 10034
Not Found: /api/blog/comments/
"GET /api/blog/comments/ HTTP/1.1" 404 9986
Not Found: /api/blog/comments/
"GET /api/blog/comments/ HTTP/1.1" 404 15741
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=2 HTTP/1.1" 404 23
Not Found: /api/blog/comments/
"GET /api/blog/comments/?article=2 HTTP/1.1" 404 23
